Gh 2
ross3834/SudokuPlayer pull request #12
Opened 2019-03-01 21:08 UTC by Ross-Alexandra

2019-03-01 21:49 UTC, Ross-Alexandra-Review requested changes
More review should be done once these changes are submitted as this was a cursory look.

2019-03-01 21:49 UTC, Ross-Alexandra-Review commented on sudoku/pattern.py
> +    def add_response(self, position: tuple, value: int, candidate_reduction=False):
Why would a response default any values..... every pattern should have this value, so this should probably be required.

2019-03-01 21:49 UTC, Ross-Alexandra-Review commented on sudoku/pattern.py
> +            pattern(list): A list of lists representing the
A list of list of ints.

2019-03-27 23:15 UTC, Ross-Alexandra commented on sudoku/pattern.py
> +    def add_response(self, position: tuple, value: int, candidate_reduction=False):
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/12/commits/d711b046a444ed30efdee3903ef0607dcd7c3d35

2019-03-27 23:15 UTC, Ross-Alexandra commented on sudoku/pattern.py
> +            pattern(list): A list of lists representing the
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/12/commits/d711b046a444ed30efdee3903ef0607dcd7c3d35

2023-06-29 13:56 UTC, closed without merging