Gh 1
ross3834/SudokuPlayer pull request #4
Opened 2019-02-09 03:59 UTC by Ross-Alexandra

2019-02-11 20:22 UTC, Ross-Alexandra-Review requested changes

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not 0 <= col_index <= 8:
Should check if validate is ```True```. If validate is ```False```, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not 0 <= row_index <= 8:
Should check if validate is `True`. If validate is `False`, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Should check if validate is `True`. If validate is `False`, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 8 and 0 <= cell_position[1] <= 8):
Should check if validate is `True`. If validate is `False`, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Should check if validate is `True`. If validate is `False`, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 2 and 0 <= cell_position[1] <= 2):
Should check if validate is `True`. If validate is `False`, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +                f"cell position: {cell_position} is not a valid cell position. Must be between"
This comment is extremely clear, it should be mentioned that its not a valid cell position *from within a box*

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Also this may not be needed. the call to get box will do the exact same call.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +            print("--------------", l, "--------------", sep="\n")
print

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        """ Checks that both the puzzle object is of the valid form, and that the puzzle does
raising from this method should *at best* have a parameter saying whether to raise an exception or not. In general, it should return either True or False. This needs to be redone, as a user of the puzzle might add a move, and want to know if that move was invalid or not, without needed to catch a bunch of exceptions.

Further, for exceptions to be thrown from this method, there should be some custom ones made (a ticket should be written for this task, as that is outside of the scope of this ticket.)

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 8 and 0 <= cell_position[1] <= 8):
Should check if validate is `True`. If validate is `False`, its perfectly possible that they've created a puzzle outside these bounds.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +    def set_cell(self, cell_position: tuple, new_val: int):
Along with a change below, an "undo move" parameter should probably be added to automatically undo a move made that is invalid.

2019-02-11 20:22 UTC, Ross-Alexandra-Review commented on sudoku/puzzle.py
> +            self.check_valid()
This should probably not raise if the "undo move" attribute to be added in proposed changes is True.

2019-02-13 20:26 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not 0 <= col_index <= 8:
Will Fix.

2019-02-13 20:26 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not 0 <= row_index <= 8:
Will Fix.

2019-02-13 20:26 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Will Fix.

2019-02-13 20:26 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 8 and 0 <= cell_position[1] <= 8):
Will Fix.

2019-02-13 20:27 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 2 and 0 <= cell_position[1] <= 2):
Will Fix.

2019-02-13 20:27 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +                f"cell position: {cell_position} is not a valid cell position. Must be between"
unclear*

 Will fix

2019-02-13 20:30 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +            print("--------------", l, "--------------", sep="\n")
Will fix

2019-02-13 20:33 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not 0 <= col_index <= 8:
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:33 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not 0 <= row_index <= 8:
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:33 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:33 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 8 and 0 <= cell_position[1] <= 8):
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:37 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Will remove second call, addressed the check in Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:37 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 2 and 0 <= cell_position[1] <= 2):
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:37 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +            print("--------------", l, "--------------", sep="\n")
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:39 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= box_position[0] <= 2 and 0 <= box_position[1] <= 2):
Removed redundancy in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/0b3593d2a1302a693448bfb4d75bb8e30c23e4c5

2019-02-13 20:41 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +                f"cell position: {cell_position} is not a valid cell position. Must be between"
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/80122a4e50fc47f74d2fb0646c22eb2e4d85958f

2019-02-13 20:42 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        if not (0 <= cell_position[0] <= 8 and 0 <= cell_position[1] <= 8):
Addressed in https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/68441c20e81967c610c7f078d2103630e11f5f92

2019-02-13 20:50 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        """ Checks that both the puzzle object is of the valid form, and that the puzzle does
Replying here for the other 2 comments (https://github.com/Ross-Alexandra/SudokuPlayer/pull/4#discussion_r255674744 and https://github.com/Ross-Alexandra/SudokuPlayer/pull/4#discussion_r255675046).



Will change `check_valid` to take a "raise" parameter. When the raise parameter is True, then exceptions will be raised should the puzzle be invalid. If it is False, then instead, `check_valid` will return True if no errors occurred, False otherwise.

If validate is set to True:
 Further, the set_cell method will now take an "undo_move" parameter. set_cell will undo an invalid move if undo_move is True. If False, then set_cell will raise an exception if an invalid move is made.

2019-02-13 21:08 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +        """ Checks that both the puzzle object is of the valid form, and that the puzzle does
Addressed with https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/e107772c5a4b1309dfe3302a2f58778ac862129e

2019-02-13 21:08 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +            self.check_valid()
Addressed with https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/e107772c5a4b1309dfe3302a2f58778ac862129e

2019-02-13 21:08 UTC, Ross-Alexandra commented on sudoku/puzzle.py
> +    def set_cell(self, cell_position: tuple, new_val: int):
Addressed with https://github.com/Ross-Alexandra/SudokuPlayer/pull/4/commits/e107772c5a4b1309dfe3302a2f58778ac862129e

2019-02-13 21:12 UTC, Ross-Alexandra-Review approved these changes

2019-02-13 21:12 UTC, merged